# Generated by Django 3.1.7 on 2021-03-14 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contents', '0002_contents_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contents',
            name='date',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
